config/routes.rb
Project::Application.routes.draw do
	resources :sessions, :only => [:new, :create, :destroy]
	resources :users
	
	match '/signin', :to => 'sessions#new'
	match '/signout', :to => 'sessions#destroy'
    match '/signup',  :to => 'users#new'
	match '/contact', :to => 'pages#contact'
	match '/about',   :to => 'pages#about'
	match '/help',    :to => 'pages#help'

	root :to => 'pages#home'

end

app/models/Administrator.rb
class Administrator < User
end

app/models/Reporter.rb
class Reporter < User
end

app/models/Teacher.rb
class Teacher < User
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  UserName   :string(255)
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

require 'digest'

class User < ActiveRecord::Base
	include SessionsHelper

	attr_accessor :password, :check
	attr_accessible :UserName, :name, :email, :password, :password_confirmation, :type
	
	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :name, :presence => true,
						:length => {:maximum => 50}
	validates :email, :presence => true,
						:format => {:with => email_regex},
						:uniqueness => true
	validates :UserName, :presence => true,
							:uniqueness => true,
							:length => {:within => 6..40}
	validates :password, :presence => true,
							:confirmation => true,
							:length => {:within => 6..40}
	before_save :encrypt_password
	
	def has_password?(submitted_password)
		encrypted_password == encrypt(submitted_password)
	end
	def self.authenticate(username, submitted_password)
		user = find_by_UserName(username)
		return nil if user.nil?
		return user if user.has_password?(submitted_password)
	end
	def self.authenticate_with_salt(id, cookie_salt)
		user = find_by_id(id)
		(user && user.salt == cookie_salt)? user : nil
	end
	
	private
		def encrypt_password
			self.salt = make_salt if new_record?
			if !check
				self.encrypted_password = encrypt(password)
			end
		end
		def encrypt(string)
			secure_hash("#{salt}--#{string}")
		end
	    def make_salt
			secure_hash("#{Time.now.utc}--#{password}")
		end

		def secure_hash(string)
			Digest::SHA2.hexdigest(string)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end
  def help
    @title = "Help"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		@title = "Sign in"
	end

	def create
		user = User.authenticate(params[:session][:UserName],
									params[:session][:password])
		if user.nil?
			flash.now[:error] = "Invalid user name or password"
			@title = "Sign in"
			render 'new'
		else
			sign_in user
			redirect_to user
		end
	end

	def destroy
		sign_out
		redirect_to root_path
	end	

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate, :only => [:edit, :update]
	before_filter :correct_user, :only => [:edit, :update]
	def new
		@title = "Sign up"
	end
	
	def show
		@user = User.find(params[:id])
	end
	def edit
		@user = User.find(params[:id])
		@tittle = "Edit user"
	end
	def update
		@user = User.find(params[:id])
		@user.name = params[:user][:name]
		@user.email = params[:user][:email]
		@user.password = "fakepass"
		@user.password_confirmation = "fakepass"
		@user.check = 0
		if @user.save
			flash[:succes] = "Profile updated"
			redirect_to @user
		else
			@title = "Edit user"
			render 'edit'
		end
	end
	
	private
		
		def authenticate
			deny_access unless signed_in?
		end
		def correct_user
			@user = User.find(params[:id])
			redirect_to(root_path) unless current_user?(@user)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Return a title on a per-page basis.
  def title
    base_title = "Ruby on Rails Tutorial Sample App"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
	def logo
		image_tag("logo.png", :alt => "Hieu's Project", :class => "round")
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		cookies.permanent.signed[:remember_token] = [user.id, user.salt]
		self.current_user = user
	end
	def current_user=(user)
		@current_user = user
	end
	def current_user
		@current_user ||= user_from_remember_token
	end
	def signed_in?
		!current_user.nil?
	end
	def sign_out
		cookies.delete(:remember_token)
		self.current_user = nil
	end
	def deny_access
		redirect_to signin_path, :notice => "Please sign in to access this page"
	end
	def current_user?(user)
		user == current_user
	end
	private
		def user_from_remember_token
			User.authenticate_with_salt(*remember_token)
		end
		def remember_token
			cookies.signed[:remember_token] || [nil, nil]
		end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
    <ul>
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "Help", help_path %></li>
		<% if signed_in? %>
		<li><%= link_to "Profile", current_user %></li>
		<li><%= link_to "Settings", edit_user_path(current_user) %></li>
		<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
		<% else %>
		<li><%= link_to "Sign in", signin_path %></li>
		<% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->    
    <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
    <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
    <%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
		<% flash.each do |key, value| %>
			<div class="flass <%= key %>"><%= value %></div>
		<% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
	  <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<p>
	This is my first project.
</p>

app/views/pages/contact.html.erb
<p>
	Please send me an email.
</p>

app/views/pages/help.html.erb
<p>You can contact us to get more information.</p>

app/views/pages/home.html.erb
<p>
	This is the home page of Hieu's project.
</p>
<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id = "error_explanation">
		<h2><%= pluralize(object.errors.count, "error") %>
				prohibited this user from being saved:</h2>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	<div class = "field">
		<%= f.label :name %><br />
		<%= f.text_field :name%>
	</div>
	<div class = "field">
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</div>
	<div class = "actions">
		<%= f.submit "Update" %>
	</div>
<% end %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>